apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  labels:
    app: speedtest-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  type: ClusterIP
  selector:
    app: speedtest-exporter
  ports:
    - name: http
      port: 5000
      targetPort: 5000
